Repository FullStackersHQ/STUDIT_FE, pull requests merged in 2025-02, with the labels that each got.

#1 Config/extra setting
  .prettierrc
  package.json
  src/App.tsx
  src/api/.gitkeep
  src/assets/icons/home.svg
  src/components/.gitkeep
  src/constants/.gitkeep
  src/custom.d.ts
  src/hooks/.gitkeep
  src/index.css
  src/layouts/.gitkeep
  src/pages/.gitkeep
  src/routes/.gitkeep
  src/store/.gitkeep
  src/styles/.gitkeep
  src/utils/.gitkeep
  tailwind.config.ts
  vite.config.ts
  yarn.lock
Labels: config

#2 Config/setting
  index.html
  package.json
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  src/assets/react.svg
  src/mocks/.gitkeep
  src/pages/CreateStudy.tsx
  src/pages/EditStudy.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/Points.tsx
  src/pages/Study.tsx
  src/pages/StudyInfo.tsx
  src/routes/.gitkeep
  src/routes/routes.tsx
  tailwind.config.ts
  yarn.lock
Labels: config

#3 [conf] tailwind 4.0 업데이트 관련 color 및 reser.css 적용
  src/App.css
  src/App.tsx
  src/assets/logo.png
  src/index.css
  tailwind.config.ts
Labels: config

#5 [feat] 레이아웃 및 공용 헤더 생성
  src/App.tsx
  src/assets/icons/chatting.svg
  src/assets/icons/chevron-left.svg
  src/assets/icons/hamburger-menu.svg
  src/assets/icons/statistics.svg
  src/assets/icons/study.svg
  src/components/.gitkeep
  src/components/HeaderWithBack.tsx
  src/components/StudyFnb.tsx
  src/layouts/.gitkeep
  src/layouts/Layout.tsx
  src/pages/Group.tsx
  src/pages/Study.tsx
  src/routes/routes.tsx
Labels: feat

#4 [feat] 메인 페이니(스터디 표시 페이지) 레이아웃 완성
  src/App.css
  src/App.tsx
  src/assets/icons/bell.svg
  src/pages/Home.tsx
Labels: feat

#7 [feat] 마이페이지 UI 및 서버 연결할 client 생성
  .prettierrc
  index.html
  package.json
  public/mockServiceWorker.js
  src/api/myPageApi.ts
  src/assets/icons/edit.svg
  src/assets/icons/point.svg
  src/components/Button.tsx
  src/components/Header.tsx
  src/components/my-page/AverageStats.tsx
  src/components/my-page/ProfileSection.tsx
  src/hooks/my-page/useAverageStats.ts
  src/hooks/my-page/useMyPage.ts
  src/hooks/my-page/useProfile.ts
  src/index.css
  src/layouts/Layout.tsx
  src/main.tsx
  src/mocks/data/dummy.ts
  src/mocks/handlers.ts
  src/mocks/myPageHandlers.ts
  src/pages/MyPage.tsx
  src/types/interface.ts
  src/utils/client.ts
  src/utils/commonUtils.ts
  yarn.lock
Labels: feat

#10 [feat] 스터디 생성 페이지 디자인
  package.json
  src/components/Fnb.tsx
  src/components/Header.tsx
  src/pages/CreateStudy.tsx
  src/pages/Search.tsx
  yarn.lock
Labels: feat

#11 [feat] 마이 페이지 프로필 수정 모달 및 공용 util 함수 구현
  package.json
  src/App.tsx
  src/api/myPageApi.ts
  src/assets/icons/close.svg
  src/components/Button.tsx
  src/components/Fnb.tsx
  src/components/Header.tsx
  src/components/ModalOverlay.tsx
  src/components/my-page/ProfileModifyModal.tsx
  src/components/my-page/ProfileSection.tsx
  src/hooks/my-page/useModifyNickName.ts
  src/hooks/my-page/useModifyProfile.ts
  src/hooks/my-page/useModifyProfileImg.ts
  src/index.css
  src/mocks/myPageHandlers.ts
  src/pages/MyPage.tsx
  src/utils/commonUtils.ts
  yarn.lock
Labels: feat

#12 [feat]: 스터디 목록 페이지 구현(참여 예정, 참여 중, 완료)
  src/api/myPageApi.ts
  src/components/HeaderWithBack.tsx
  src/components/my-page/StudyItem.tsx
  src/hooks/my-page/useFetchStudyList.ts
  src/hooks/my-page/useStudyList.ts
  src/mocks/data/dummy.ts
  src/mocks/myPageHandlers.ts
  src/pages/StudyList.tsx
  src/routes/routes.tsx
  src/types/interface.ts
Labels: feat

#13 [feat] 마이 페이지와 스터디 목록 페이지 연결 및 마이 페이지 높이 설정
  src/components/my-page/AverageStats.tsx
  src/components/my-page/ProfileSection.tsx
  src/layouts/Layout.tsx
  src/mocks/data/dummy.ts
  src/pages/MyPage.tsx
Labels: feat

#15 [Refactor] main
  package.json
  src/components/create-study/Calendar.tsx
  src/components/home/StudyRoom.tsx
  src/mocks/data/dummy.ts
  src/pages/CreateStudy.tsx
  src/pages/Home.tsx
  src/types/createStudyType.ts
  yarn.lock
Labels: refactoring

#16 [chore] GitHub Actions를 사용하여 자동 배포 시스템 설정
  .github/workflows/deploy.yml
  vite.config.ts
Labels: chore

#17 fix: Aws 리전 시크릿 명 변경
  .github/workflows/deploy.yml
Labels: chore

#18 [feat] 포인트 페이지 UI 구현 및 msw 바인딩
  src/api/.gitkeep
  src/api/pointApi.ts
  src/assets/icons/deduct.svg
  src/assets/icons/topup.svg
  src/assets/icons/withdraw.svg
  src/components/HeaderWithBack.tsx
  src/components/my-page/AverageStats.tsx
  src/components/point/PointCheck.tsx
  src/components/point/PointFilterList.tsx
  src/components/point/PointHistory.tsx
  src/components/point/PointRecordItem.tsx
  src/components/search/Category.tsx
  src/constants/.gitkeep
  src/constants/CATEGORY.ts
  src/constants/constants.ts
  src/hooks/point/useGetPointHistory.ts
  src/hooks/point/useGetUserPoints.ts
  src/mocks/data/dummy.ts
  src/mocks/handlers.ts
  src/mocks/pointHandlers.ts
  src/pages/CreateStudy.tsx
  src/pages/MyPage.tsx
  src/pages/Point.tsx
  src/pages/Points.tsx
  src/pages/StudyList.tsx
  src/routes/routes.tsx
  src/types/interface.ts
  src/utils/commonUtils.ts
Labels: feat

#19 [feat] msw 바인딩
  src/components/home/FilterList.tsx
  src/mocks/data/dummy.ts
  src/mocks/studyRoomHandlers.ts
  src/pages/CreateStudy.tsx
  src/pages/Home.tsx
  src/types/createStudyType.ts
  src/types/interface.ts
Labels: feat

#22 Fix/create study
  src/App.css
  src/components/create-study/Calendar.tsx
  src/components/home/StudyRoom.tsx
  src/components/home/StudyRoomList.tsx
  src/mocks/data/dummy.ts
  src/mocks/studyRoomHandlers.ts
  src/pages/CreateStudy.tsx
Labels: fix

#23 [feat] 포인트 출금 모달 UI 구현 및 msw 바인딩
  src/App.css
  src/api/pointApi.ts
  src/components/my-page/ProfileModifyModal.tsx
  src/components/point/PointCheck.tsx
  src/components/point/PointHistory.tsx
  src/components/point/WithdrawModal.tsx
  src/hooks/.gitkeep
  src/hooks/point/useGetPointHistory.ts
  src/hooks/point/useGetUserPoints.ts
  src/hooks/point/useWithdrawModal.ts
  src/hooks/point/useWithdrawPoint.ts
  src/mocks/data/dummy.ts
  src/mocks/pointHandlers.ts
  src/styles/.gitkeep
  src/types/interface.ts
Labels: feat

#24 [feat] 스터디 모집 페이지 ui
  src/App.css
  src/api/recruitApi.ts
  src/components/home/FilterList.tsx
  src/components/home/StudyRoom.tsx
  src/components/home/StudyRoomList.tsx
  src/components/recruit/DeleteModal.tsx
  src/components/recruit/PointShortageModal.tsx
  src/mocks/data/dummy.ts
  src/mocks/studyRoomHandlers.ts
  src/pages/CreateStudy.tsx
  src/pages/StudyInfo.tsx
  src/pages/StudyRecruit.tsx
  src/routes/routes.tsx
  src/types/interface.ts
Labels: feat

#27 [feat] 스터디 수정 페이지 UI 구현 및 msw 바인딩
  src/App.css
  src/api/studyApi.ts
  src/components/Button.tsx
  src/components/my-page/ProfileModifyModal.tsx
  src/components/point/PointCheck.tsx
  src/components/point/PointHistory.tsx
  src/components/point/WithdrawModal.tsx
  src/hooks/study-default/useEditStudy.ts
  src/hooks/study-default/useGetStudyDetail.ts
  src/hooks/study-default/useStudyMutation.ts
  src/mocks/data/dummy.ts
  src/mocks/handlers.ts
  src/mocks/pointHandlers.ts
  src/mocks/studyHandlers.ts
  src/pages/EditStudy.tsx
  src/pages/MyPage.tsx
  src/pages/StudyList.tsx
  src/types/commonInterface.ts
  src/types/interface.ts
  src/types/request.ts
  src/utils/.gitkeep
  src/utils/commonUtils.ts
Labels: feat

#29 [design] 컬러 시스템 변경
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/vite.svg
  src/App.css
  src/assets/logo.png
  src/assets/logo.webp
  src/components/Button.tsx
  src/components/Fnb.tsx
  src/components/Header.tsx
  src/components/HeaderWithBack.tsx
  src/components/StudyFnb.tsx
  src/components/my-page/AverageStats.tsx
  src/components/my-page/ProfileModifyModal.tsx
  src/components/my-page/ProfileSection.tsx
  src/components/point/PointFilterList.tsx
  src/index.css
  src/layouts/Layout.tsx
  src/pages/EditStudy.tsx
  src/pages/Point.tsx
Labels: design

#32 [feat] 스터디 기본 페이지 투두 리스트 섹션 UI 구현 및 msw 바인딩
  src/api/studyApi.ts
  src/api/studyMainApi.ts
  src/assets/icons/play.svg
  src/components/my-page/ProfileSection.tsx
  src/components/study-main/TodoListSection.tsx
  src/hooks/study-main/edit/useEditStudy.ts
  src/hooks/study-main/edit/useStudyMutation.ts
  src/hooks/study-main/useCreateTodo.ts
  src/hooks/study-main/useEditTodo.ts
  src/hooks/study-main/useGetStudyDetail.ts
  src/hooks/study-main/useGetTodoList.ts
  src/hooks/study-main/useStudyDefault.ts
  src/hooks/study-main/useTodoActions.ts
  src/hooks/study-main/useTodoList.ts
  src/hooks/study-main/useTodoState.ts
  src/hooks/study-main/useToggleTodo.ts
  src/mocks/data/dummy.ts
  src/mocks/handlers.ts
  src/mocks/pointHandlers.ts
  src/mocks/studyHandlers.ts
  src/mocks/studyMainHandlers.ts
  src/pages/EditStudy.tsx
  src/pages/Study.tsx
  src/pages/StudyMain.tsx
  src/routes/routes.tsx
  src/types/interface.ts
  src/types/request.ts
Labels: feat

#34 Feat/login
  src/api/oauthApi.ts
  src/assets/img/kakao-login-large-wide.png
  src/components/home/FilterList.tsx
  src/components/search/Category.tsx
  src/components/search/RangeSlider.tsx
  src/components/search/WeekStudyTime.tsx
  src/constants/oauth.ts
  src/mocks/handlers.ts
  src/mocks/kakaoHandlers.ts
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/Search.tsx
  src/pages/StudyRoom.tsx
  src/store/useAuthStore.ts
  src/store/useSearchStore.ts
Labels: feat

#35 [feat] 스터디 기본 페이지 스터디 나가기, 공지 등록, 공지 수정 UI 구현 및 msw 바인딩
  src/App.css
  src/api/studyMainApi.ts
  src/components/HeaderWithBack.tsx
  src/components/my-page/ProfileModifyModal.tsx
  src/components/point/WithdrawModal.tsx
  src/components/study-main/LeaveStudyModal.tsx
  src/components/study-main/ManageNoticeModal.tsx
  src/components/study-main/StudyMenuList.tsx
  src/components/study-main/TodoListSection.tsx
  src/hooks/study-main/todo/useCreateTodo.ts
  src/hooks/study-main/todo/useEditTodo.ts
  src/hooks/study-main/todo/useGetTodoList.ts
  src/hooks/study-main/todo/useTodoActions.ts
  src/hooks/study-main/todo/useTodoList.ts
  src/hooks/study-main/todo/useTodoState.ts
  src/hooks/study-main/todo/useToggleTodo.ts
  src/hooks/study-main/useCreateNotice.ts
  src/hooks/study-main/useEditNotice.ts
  src/hooks/study-main/useGetNotice.ts
  src/hooks/study-main/useGetStudyDetail.ts
  src/hooks/study-main/useNoticeModal.ts
  src/hooks/study-main/useStudyDefault.ts
  src/hooks/study-main/useStudyMain.ts
  src/mocks/data/dummy.ts
  src/mocks/studyMainHandlers.ts
  src/pages/StudyMain.tsx
  src/types/interface.ts
  src/types/request.ts
  src/utils/commonUtils.ts
Labels: feat

#36 [rename]route 및 폴더 이름 변경
  src/components/Fnb.tsx
  src/components/Study-list/StudyRoomList.tsx
  src/components/my-page/ProfileSection.tsx
  src/components/recruitList/FilterList.tsx
  src/components/recruitList/StudyRecruitList.tsx
  src/components/study-detail/LeaveStudyModal.tsx
  src/components/study-detail/ManageNoticeModal.tsx
  src/components/study-detail/StudyMenuList.tsx
  src/components/study-detail/TodoListSection.tsx
  src/hooks/my-page/useFetchMyStudyList.ts
  src/hooks/my-page/useMyStudyList.ts
  src/hooks/recruit/useEditRecruit.ts
  src/hooks/recruit/useGetRecruitInfo.ts
  src/hooks/recruit/useRecruitMutation.ts
  src/hooks/study-detail/edit/useEditStudy.ts
  src/hooks/study-detail/edit/useStudyMutation.ts
  src/hooks/study-detail/todo/useCreateTodo.ts
  src/hooks/study-detail/todo/useEditTodo.ts
  src/hooks/study-detail/todo/useGetTodoList.ts
  src/hooks/study-detail/todo/useTodoActions.ts
  src/hooks/study-detail/todo/useTodoList.ts
  src/hooks/study-detail/todo/useTodoState.ts
  src/hooks/study-detail/todo/useToggleTodo.ts
  src/hooks/study-detail/useCreateNotice.ts
  src/hooks/study-detail/useEditNotice.ts
  src/hooks/study-detail/useGetNotice.ts
  src/hooks/study-detail/useGetStudyDetail.ts
  src/hooks/study-detail/useNoticeModal.ts
  src/hooks/study-detail/useStudyMain.ts
  src/layouts/Layout.tsx
  src/mocks/studyMainHandlers.ts
  src/pages/EditRecruit.tsx
  src/pages/EditStudy.tsx
  src/pages/Home.tsx
  src/pages/MyStudyList.tsx
  src/pages/RecruitDetail.tsx
  src/pages/RecruitList.tsx
  src/pages/StudyDetail.tsx
  src/pages/StudyList.tsx
  src/routes/routes.tsx
Labels: refactoring

#39 Feat/statistics
  src/components/study-detail/statistics/GroupGraph.tsx
  src/components/study-detail/statistics/Statistics.tsx
  src/components/study-detail/statistics/UserDailyGraph.tsx
  src/components/study-detail/statistics/UserGraph.tsx
  src/components/study-detail/statistics/UserWeeklyGraph.tsx
  src/constants/constants.ts
  src/pages/StudyDetail.tsx
  src/types/staticInterface.ts
  src/utils/commonUtils.ts
Labels: feat

#40 Fix/statistics
  src/components/study-detail/statistics/GroupGraph.tsx
  src/components/study-detail/statistics/Statistics.tsx
  src/components/study-detail/statistics/UserWeeklyGraph.tsx
Labels: fix

#41 [feat] 마이 페이지 스터디 목록 인피니트 스크롤 적용
  src/api/myPageApi.ts
  src/api/pointApi.ts
  src/components/my-page/StudyItem.tsx
  src/components/point/WithdrawModal.tsx
  src/hooks/my-page/useFetchMyStudyList.ts
  src/hooks/my-page/useMyStudyList.ts
  src/mocks/data/dummy.ts
  src/mocks/myPageHandlers.ts
  src/mocks/pointHandlers.ts
  src/mocks/studyMainHandlers.ts
  src/pages/MyStudyList.tsx
  src/types/interface.ts
Labels: feat

#42 [hotfix] constants 파일에 누락된 보상, 환불 포인트 필터 추가
  src/constants/constants.ts
Labels: hotfix

#43 hotfix: 클라이언트 url 변경
  src/utils/client.ts
Labels: hotfix

#45 Fix/kakao login
  src/api/oauthApi.ts
  src/components/Header.tsx
  src/constants/constants.ts
  src/constants/oauth.ts
  src/layouts/Layout.tsx
  src/layouts/LoginRequiredLayout.tsx
  src/main.tsx
  src/mocks/kakaoHandlers.ts
  src/pages/Login.tsx
  src/pages/LoginRedirect.tsx
  src/pages/RecruitList.tsx
  src/pages/StudyList.tsx
  src/routes/routes.tsx
Labels: fix

#46 [feat] 스터디 상세 페이지 타이머 UI 구현 및 msw바인딩
  src/App.css
  src/api/studyMainApi.ts
  src/assets/icons/bell.svg
  src/assets/icons/chatting.svg
  src/assets/icons/leader.svg
  src/assets/icons/light-off.svg
  src/assets/icons/light-on.svg
  src/assets/icons/pause.svg
  src/assets/icons/statistics.svg
  src/assets/icons/study.svg
  src/components/StudyFnb.tsx
  src/components/study-detail/StudyMenuList.tsx
  src/components/study-detail/main/CreateTodo.tsx
  src/components/study-detail/main/LeaveStudyModal.tsx
  src/components/study-detail/main/ManageNoticeModal.tsx
  src/components/study-detail/main/Notice.tsx
  src/components/study-detail/main/NoticeModal.tsx
  src/components/study-detail/main/StudyMenuList.tsx
  src/components/study-detail/main/Timers.tsx
  src/components/study-detail/main/TodoListSection.tsx
  src/hooks/study-detail/todo/useTodoList.ts
  src/hooks/study-detail/todo/useTodoTimer.ts
  src/hooks/study-detail/useGetTimers.ts
  src/hooks/study-detail/useStudyMain.ts
  src/hooks/study-detail/useTimers.ts
  src/hooks/study-detail/useToggleTimer.ts
  src/mocks/data/dummy.ts
  src/mocks/studyMainHandlers.ts
  src/pages/Statistics.tsx
  src/pages/StudyDetail.tsx
  src/routes/routes.tsx
  src/types/interface.ts
  src/types/request.ts
  src/utils/commonUtils.ts
Labels: feat

#48 feat: 포인트 충전하기 기능 UI 구현 및 msw 바인딩
  src/api/pointApi.ts
  src/components/my-page/ChargeModal.tsx
  src/components/my-page/ProfileSection.tsx
  src/hooks/my-page/useChargeModal.ts
  src/hooks/my-page/useChargePoint.ts
  src/hooks/point/useWithdrawModal.ts
  src/mocks/pointHandlers.ts
  src/types/request.ts
Labels: feat

#49 Refactor/recruit detail
  package.json
  src/App.css
  src/assets/lottie/spinner.json
  src/components/LoadingScreen.tsx
  src/components/recruit/LeaderMenuList.tsx
  src/components/recruit/PointShortageModal.tsx
  src/components/recruit/RecruitSuccessModal.tsx
  src/layouts/Layout.tsx
  src/mocks/data/dummy.ts
  src/mocks/data/pointMockData.ts
  src/mocks/data/studyDetailMockData.ts
  src/mocks/data/studyListMockData.ts
  src/mocks/data/userMockData.ts
  src/mocks/kakaoHandlers.ts
  src/mocks/myPageHandlers.ts
  src/mocks/pointHandlers.ts
  src/mocks/recruitHandlers.ts
  src/mocks/studyMainHandlers.ts
  src/pages/Home.tsx
  src/pages/LoginRedirect.tsx
  src/pages/RecruitDetail.tsx
  src/routes/routes.tsx
  yarn.lock
Labels: fix, refactoring

#50 fix: 실시간 서버 동기화 타이머 시스템 구축
  .gitignore
  package.json
  src/App.css
  src/components/LoadingScreen.tsx
  src/components/study-detail/main/ManageNoticeModal.tsx
  src/components/study-detail/main/Notice.tsx
  src/components/study-detail/main/TodoListSection.tsx
  src/hooks/study-detail/notice/useCreateNotice.ts
  src/hooks/study-detail/notice/useDeleteNotice.ts
  src/hooks/study-detail/notice/useEditNotice.ts
  src/hooks/study-detail/notice/useGetNotice.ts
  src/hooks/study-detail/notice/useManageModal.ts
  src/hooks/study-detail/notice/useNoticeModal.ts
  src/hooks/study-detail/timers/useGetTimers.ts
  src/hooks/study-detail/timers/useSyncWithServer.ts
  src/hooks/study-detail/timers/useTodoNTimers.ts
  src/hooks/study-detail/timers/useToggleTimer.ts
  src/hooks/study-detail/todo/useTodoList.ts
  src/hooks/study-detail/todo/useTodoTimer.ts
  src/hooks/study-detail/useTimers.ts
  src/layouts/Layout.tsx
  src/main.tsx
  src/mocks/handlers.ts
  src/mocks/studyMainHandlers.ts
  src/mocks/timerHandlers.ts
  src/mocks/todoHandlers.ts
  src/pages/StudyDetail.tsx
  src/utils/client.ts
  vite.config.ts
  yarn.lock
Labels: fix

#52 [fix] 검색창 UI 변경
  src/App.css
  src/components/search/Category.tsx
  src/components/search/RangeSlider.tsx
  src/components/search/Select.tsx
  src/components/search/WeekStudyTime.tsx
  src/constants/constants.ts
  src/pages/Search.tsx
  src/store/useSearchStore.ts
Labels: fix

#53 [feat] 데이터 미존재 시 UI 처리 및 최상단으로 이동하는 버튼 구현
  package.json
  src/assets/icons/arrow-up.svg
  src/assets/icons/chevron-right.svg
  src/assets/icons/default-profile.svg
  src/assets/imgs/banner.png
  src/assets/imgs/default-profile.webp
  src/assets/imgs/empty-point.png
  src/assets/imgs/empty-study-list.png
  src/components/Fnb.tsx
  src/components/ScrollToTopBtn.tsx
  src/components/my-page/AverageStats.tsx
  src/components/my-page/StudyItem.tsx
  src/components/my-page/ThreeDotsLoader.tsx
  src/components/point/PointHistory.tsx
  src/components/point/PointRecordItem.tsx
  src/constants/constants.ts
  src/hooks/my-page/useMyStudyList.ts
  src/hooks/useIntersectionObserver.tsx
  src/mocks/data/userMockData.ts
  src/mocks/pointHandlers.ts
  src/pages/MyStudyList.tsx
  src/pages/Point.tsx
  yarn.lock
Labels: feat

#54 Refactor/list
  src/App.css
  src/components/Fnb.tsx
  src/components/home/OngoingList.tsx
  src/components/home/RecruitList.tsx
  src/constants/constants.ts
  src/mocks/data/studyDetailMockData.ts
  src/mocks/data/studyListMockData.ts
  src/pages/Home.tsx
  src/types/staticInterface.ts
Labels: fix, refactoring

#55 feat: 더미 데이터 변경
  index.html
  src/components/my-page/AverageStats.tsx
  src/components/point/PointHistory.tsx
  src/components/study-detail/main/Timers.tsx
  src/hooks/study-detail/timers/useGetTimers.ts
  src/hooks/study-detail/todo/useGetTodoList.ts
  src/hooks/study-detail/useGetStudyDetail.ts
  src/mocks/data/pointMockData.ts
  src/mocks/data/studyDetailMockData.ts
  src/mocks/data/studyListMockData.ts
  src/mocks/data/userMockData.ts
  src/mocks/studyMainHandlers.ts
  src/pages/MyStudyList.tsx
  src/types/interface.ts
  src/utils/commonUtils.ts
Labels: feat

#56 [feat] 토스트 기능 생성
  src/App.css
  src/App.tsx
  src/assets/icons/check.svg
  src/components/Toast.tsx
  src/hooks/my-page/useChargeModal.ts
  src/hooks/point/useWithdrawModal.ts
  src/hooks/study-detail/edit/useStudyMutation.ts
  src/pages/CreateStudy.tsx
  src/store/.gitkeep
  src/store/useToastStore.ts
Labels: feat

#57 [chore] 배포 과정에서 .env 파일이 자동으로 생성되도록 설정
  .github/workflows/deploy.yml
Labels: chore

#58 [design] 배너 색상 변경 및 스타일 개선
  src/assets/icons/chevron-right.svg
  src/pages/MyStudyList.tsx
Labels: design

#59 [chore] kakao redirect uri 값 배포 env에 추가
  .github/workflows/deploy.yml
Labels: chore

#61 [optimise] 성능 최적화 및 QA 진행에 따른 변경
  .github/workflows/deploy.yml
  index.html
  public/mockServiceWorker.js
  public/robots.txt
  src/api/studyMainApi.ts
  src/assets/imgs/og-image.png
  src/components/Button.tsx
  src/components/Header.tsx
  src/components/point/PointCheck.tsx
  src/components/study-detail/main/Notice.tsx
  src/components/study-detail/main/NoticeModal.tsx
  src/components/study-detail/main/Timers.tsx
  src/components/study-detail/main/TodoListSection.tsx
  src/hooks/study-detail/timers/useSyncWithServer.ts
  src/hooks/study-detail/timers/useTodoNTimers.ts
  src/main.tsx
  src/mocks/data/studyListMockData.ts
  src/mocks/studyMainHandlers.ts
  src/mocks/todoHandlers.ts
  src/pages/MyPage.tsx
  src/pages/Point.tsx
  src/pages/StudyDetail.tsx
  src/types/interface.ts
Labels: optimise

#62 [design] qa에 따른 변경사항 적용
  src/App.css
  src/components/study-detail/main/StudyMenuList.tsx
  src/pages/MyPage.tsx
Labels: design
